language: python
dist: trusty

python:
  - "2.7"
  
install:
 - sudo apt-get install erlang erlang-doc
 - sudo apt-get install rabbitmq-server
 - pip install flake8 autopep8
 - pip install pika
 - pip install Django==1.8.16
 - pip install gunicorn==19.6.0
script:
  - python manage.py test
  - flake8 --max-line-length=160 --exclude=*.pyc *.py
  
