# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMedicamento', models.IntegerField()),
                ('horaInicial', models.DateTimeField()),
                ('periodo', models.IntegerField()),
                ('dosis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.TextField(max_length=100)),
                ('edad', models.IntegerField(max_length=150)),
                ('idWeareble', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.Medicamento'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.Miembro'),
        ),
    ]
